### ISSUE TITLE
Installation fails because of lodashbuilder

### ISSUE THREAD

**Issue by sbaechler** [bauschan/generator-zurb-foundation#11]
When trying to install the zurb-foundation package which has a dependency on this package, installation fails with the following message:

```
> grunt-lodashbuilder@0.1.7 postinstall /Users/sb/projects/hslu-iosslider/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder
> node ./bin/post-install.js


module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/lodash/vendor/tar/tar.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at /Users/sb/projects/hslu-iosslider/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:14:13
    at Object.<anonymous> (/Users/sb/projects/hslu-iosslider/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:166:2)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm http 304 https://registry.npmjs.org/inherits
npm ERR! grunt-lodashbuilder@0.1.7 postinstall: `node ./bin/post-install.js`
npm ERR! `sh "-c" "node ./bin/post-install.js"` failed with 1
npm ERR! 
npm ERR! Failed at the grunt-lodashbuilder@0.1.7 postinstall script.
npm ERR! This is most likely a problem with the grunt-lodashbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/post-install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-lodashbuilder
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/sb/projects/hslu-iosslider
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! code ELIFECYCLE
npm ERR! message grunt-lodashbuilder@0.1.7 postinstall: `node ./bin/post-install.js`
npm ERR! message `sh "-c" "node ./bin/post-install.js"` failed with 1
npm ERR! Error: ENOENT, lstat '/Users/sb/projects/hslu-iosslider/node_modules/grunt-requirejs/node_modules/grunt-jquerybuilder/node_modules/jquery-builder/dist/1.8.3/jquery-deprecated.js'
npm ERR!  { [Error: ENOENT, lstat '/Users/sb/projects/hslu-iosslider/node_modules/grunt-requirejs/node_modules/grunt-jquerybuilder/node_modules/jquery-builder/dist/1.8.3/jquery-deprecated.js']
```

The package https://github.com/asciidisco/grunt-lodashbuilder is no longer maintained. It has been replaced by https://github.com/lodash/grunt-lodash

**Comment by bauschan** [comment]
Dependencies are fixed in v0.3.5
